<?php $f3 = \Base::instance() ?>
<?php
$analytics = $f3->get('analytics');
$analytics['enabled'] = $analytics['enabled'] && $f3->get('application.environment') == 'production';
?>
<?php if (!empty($analytics['enabled']) && !empty($analytics['code']) && !empty($analytics['domain'])): ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?=$analytics['code'] ?>', '<?=$analytics['domain'] ?>');
  ga('send', 'pageview');
</script>
<?php endif ?>

<?php if ($f3->get('application.environment') == 'production'): ?>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
<?php else: ?>
    <script src="/minify/js?files=/js/bootstrap.min.js"></script>
    <script src="/minify/js?files=/js/site.js"></script>
<?php endif; ?>
<hr/>
<p>Site built with: <a href="https://github.com/vijinho/f3-boilerplate">f3-boilerplate</a>

</body>
</html>
