<?php $f3 = \Base::instance() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=empty($title) ? 'f3-boilerplate' : $title ?></title>
    <meta name="description" content="<?=empty($description) ? '' : $description ?>">
    <meta name="keywords" content="<?=empty($keywords) ? '' : $keywords ?>">
    <?php /* <link rel="alternate" type="application/rss+xml" href="/rss.xml" title="RSS"> */ ?>
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0,minimal-ui">
    <meta name="HandheldFriendly" content="True"/>
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
<?php if ($f3->get('application.environment') == 'production'): ?>
    <link rel="stylesheet" href="/minify/css?files=/css/bootstrap.css,/css/style.css,/css/messages.css">
<?php else: ?>
    <link rel="stylesheet" href="/minify/css?files=/css/bootstrap.css,/css/style.css,/css/messages.css">
<?php endif ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="icon" type="image/png" href="/img/favicon.png">
</head>
<body>
<!-- Add your site or application content here -->
