<?php
$f3 = \Base::instance();
$title = $f3->get('title');
?>
<?=\View::instance()->render('www/header.phtml'); ?>
<?=\View::instance()->render('www/header-menu.phtml'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <h1><?=$title ?></h1>

            <?=\View::instance()->render('www/notifications.phtml') ?>

            <?=$f3->get('html') ?>

        </div>
    </div>
</div>

<?=\View::instance()->render('www/footer-menu.phtml'); ?>
<?=\View::instance()->render('www/footer.phtml'); ?>
