<?php
$f3 = \Base::instance();
$e = $f3->get('ERROR');
$title = 'Error:' . $e['code'];
$f3->set('title', $title);
?>
<?=\View::instance()->render('www/header.phtml'); ?>

<h1><?=$title ?></h1>

<p>
<em><?=$e['status']?></em><br/>
We're sorry but an error occurred.  Our best muppets are on the case.
</p>

<?php if ($f3->get('application.environment') !== 'production'): ?>
<h2>Error Context</h2>
<pre>
<?=$e['text'] ?>
</pre>

<h2>Error Trace</h2>
<pre>
    <?=nl2br($e['trace']) ?>
</pre>

<h2>F3 Hive</h2>
<pre>
    <?php var_dump($f3->hive()) ?>
</pre>
<?php endif ?>

<?=\View::instance()->render('www/footer.phtml'); ?>
