<?php $e = $f3->get('ERROR'); ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Error: <?=$e['code'] ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
</head>
<body>
<h1>Error: <?=$e['code'] ?></h1>

<p><em><?=$e['status']?></em><br/></p>

<?php if ($f3->get('application.environment') !== 'production'): ?>
<h2>Error Context</h2>
<pre>
<?=$e['text'] ?>    
</pre>

<h2>Error Trace</h2>
<pre>
<?=$e['trace'] ?>    
</pre>
<?php endif ?>

<hr/>
</body>
</html>
