<?php $f3 = \Base::instance() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?=empty($title) ? 'f3-boilerplate' : $title ?></title>
    <meta name="description" content="<?=empty($description) ? '' : $description ?>">
    <meta name="keywords" content="<?=empty($keywords) ? '' : $keywords ?>">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0,minimal-ui">
    <meta name="HandheldFriendly" content="True"/>
<?php if ($f3->get('application.environment') == 'production'): ?>
    <?php else: ?>
<?php endif ?>
    <link rel="stylesheet" href="/minify/css?files=/css/style.css">
    <link rel="icon" type="image/png" href="/img/favicon.png">
</head>
<body>
<!-- Add your site or application content here -->
