<?php
$f3 = \Base::instance();
// display all messages
$messages = $messages = \FFMVC\Helpers\Notifications::instance()->get();
if (is_array($messages)):
    echo '<div id="messages">';
    foreach ($messages as $type => $msgs):
        foreach ($msgs as $message):
            echo ('<div role="alert" class="alert alert-' . $type . '">' . $message . '</div>');
        endforeach;
    endforeach;
    echo '</div>';
endif;
?>
