<?php $f3 = \Base::instance();
$title = 'Home';
$f3->set('title', $title);
?>
<?=\View::instance()->render('www/header.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="eight columns">

            <h1>f3-boilerplate</h1>

            <?=\View::instance()->render('www/messages.phtml'); ?>

            <p>This project is by <a href="http://about.me/vijay.mahrra">Vijay Mahrra</a> and it is built on, and serves as, an example of the <a href="http://fatfreeframework.com/home">Fat-Free Framework</a></p>

            <h1>Rest API</h1>

            <ul>
                <li><a href="/api/">API (JSON)</a>
                <li><a href="/api?return=xml">API (XML)</a>
                <li><a href="/api/test/request">Test Request (JSON)</a>
                <li><a href="/api/test/request?return=xml">Test Request (XML)</a>
            </ul>

            <h2>Installation</h2>

            <h3>File Permissions</h3>
            <pre>
<?php
foreach (array('LOGS', 'UPLOADS', 'TEMP') as $dir) {
    if (!is_writable($f3->get($dir))) {
        print "Directory: $dir NOT writable!\n";
    } else {
        print "Directory: $dir writable.\n";
    }
}
?>
            </pre>
<?php
$db = \Registry::get('db');
if (!empty($db)) {
?>

            <h3>Database</h3>
            <pre>
<?php
    try {
        $db = \Registry::get('db');
        $result = $db->exec('SHOW TABLES');
        print "Database: Connection OK.\n";
    } catch (Exception $ex) {
        print "Database failure!\n" . print_r($ex,1);
    }
}
?>
            </pre>

            <h3>Geo-location</h3>
            <pre>
            <?php
            $geo = \Web\Geo::instance();
            var_dump($geo->location()); // locate client IP
            ?>
            </pre>

            <h3>Your device</h3>
            <p>
            <?php
            $audit = \Audit::instance();
            $bot = $audit->isbot();
            if ($bot) {
                print "You are a bot!";
            } else {
                $desktop = $audit->isdesktop();
                if ($desktop) {
                    print "You are on a desktop device!";
                } else {
                    $mobile = $audit->ismobile();
                    if ($mobile) {
                        print "You are on a mobile device!";
                    }
                }
            }
            ?>
            </p>

            <h3>Helpers</h3>
            <h4>Time/Date</h4>
            The example helper in lib/helpers/time.php can output the date/time in a mysql database format like '<?=\FFMVC\Helpers\Time::database() ?>' or for an http header '<?=\FFMVC\Helpers\Time::HTTP() ?>'

            <h4>String</h4>
            <ul>
                <li>Random String: <?=\FFMVC\Helpers\String::random(20) ?></li>
                <li>Hashed+Salted String: <?=\FFMVC\Helpers\String::salted(time(),
                    'f3-boilerplate') ?></li>
            </ul>

            <h2>Documentation</h2>
            <ul>
                <li><a href="/doc/README">README</a></li>
                <li><a href="/doc/CHANGES">CHANGES</a></li>
                <li><a href="/doc/TODO">TODO</a></li>
                <li><a href="/doc/ROADMAP">ROADMAP</a></li>
                <li><a href="/doc/LICENSE">LICENSE</a></li>
                <li><a href="/doc/CREDITS">CREDITS</a></li>
            </ul>

            <h2>PHPINFO</h2>

            <div class="phpinfo">
            <?php phpinfo() ?>
            </div>

      </div>
    </div>
  </div>

<?=\View::instance()->render('www/footer.phtml'); ?>
