<?php $f3 = \Base::instance() ?>
<?php echo \View::instance()->render('www/header.phtml'); ?>

<h1>f3-boilerplate</h1>

<p>This project is built on the <a href="http://fatfreeframework.com/home">Fat-Free Framework</a></p>

<h2>International Welcome</h2>
<p>In the i18n/ folder there are translations for English, Swedish and Spanish for the text<br/>i18n.welcome: <b><?php echo $f3->get('i18n.welcome'); ?></b></p>

<h3>Geo-location</h3>
<pre>    
<?php
$geo = \Web\Geo::instance();
var_dump($geo->location()); // locate client IP
?>
</pre>

<h3>Your device</h3>
<p>
<?php
$audit = \Audit::instance();
$bot = $audit->isbot();
if ($bot) {
    print "You are a bot!";
} else {
    $desktop = $audit->isdesktop();
    if ($desktop) {
        print "You are on a desktop device!";
    } else {
        $mobile = $audit->ismobile();
        if ($mobile) {
            print "You are on a mobile device!";
        }
    }
}
?>
</p>

<h3>Helper</h3>
The example helper in lib/helpers/time.php can output the date/time in a mysql database format like '<?php echo \FFMVC\Helpers\Time::database() ?>' or for an http header '<?php echo \FFMVC\Helpers\Time::HTTP() ?>'

<h2>Documentation</h2>
<ul>
    <li><a href="/doc/CHANGES">CHANGES</a></li>
    <li><a href="/doc/TODO">TODO</a></li>
    <li><a href="/doc/ROADMAP">ROADMAP</a></li>
    <li><a href="/doc/LICENSE">LICENSE</a></li>
    <li><a href="/doc/CREDITS">CREDITS</a></li>
</ul>

<h2>PHPINFO</h2>

<?php phpinfo() ?>

<?php echo \View::instance()->render('www/footer.phtml'); ?>
