<?php
$e = $f3->get('ERROR');

function highlight_with_linenum($file, $line = null, $offset = 8)
{
    // read the file
    $lines = file($file);

    // fix to start array at 1:
    array_unshift($lines, null);
    unset($lines[0]);

    // get lines to show
    $total = count($lines);
    $before = $line - $offset;
    if ($before < 0)
        $before = 0;
    $after = $line + $offset;
    if ($after > $total)
        $after = $total;

    // extract the codeblock
    $codeblock = array();
    for ($i = $before; $i < $after; $i++) {
        $codeblock[$i] = $lines[$i];
    }

    // format the codeblock for display
    $string = "<table>";
    foreach ($codeblock as $l => $code) {
        if ($l == $line) {
            $string .= sprintf("<tr><td>%s</td><td><b>%s</b></td></tr>", $l, highlight_string($code, true));
        } else {
            $string .= sprintf("<tr><td>%s</td><td>%s</td></tr>", $l, highlight_string($code, true));
        }
    }
    $string .= "</table>";

    return $string;
}
?>
<!DOCTYPE html>
<html>
<head>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Error: <?php echo $e['code'] ?> - <?php echo $e['text'] ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="/css/normalize.css">
        <link rel="stylesheet" href="/css/main.css">
        <script src="/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->

<h1>Error: <?php echo $e['code'] ?></h1>

<h2><?php echo $e['text'] ?></b></h2>

<table>
<tbody>
<?php foreach ($e['trace'] as $i => $t): ?>
<tr>
    <?php printf('<td>%d</td><td><h3><input type="text" size="%d" value="%s"/>:%d</h3>', $i, strlen($t['file']), $t['file'], $t['line']) ?>
    <?php echo highlight_with_linenum($t['file'], $t['line']); ?>
    <?php if (!empty($t['class'])): ?><?php printf("<br/>%s %s ", $t['class'], $t['type']) ?><?php endif ?>
    <?php if (!empty($t['function'])): ?><?php printf("%s()", $t['function']) ?><?php endif ?>
    </td>
</tr>
<?php if (!empty($t['args'])): ?>
<tr>
    <td></td>
    <td colspan="2"><pre><?php print_r($t['args']) ?></pre></td>
</tr>
<?php endif ?>
<?php endforeach ?>
</tbody>
<tfooter>

</tfooter>
</table>

<hr/>

    </body>
</html>
