<?php
$f3    = \Base::instance();
$e     = $f3->get('ERROR');
$title = 'Error: ' . $e['code'];
$f3->set('title', $title);
$debug = $f3->get('DEBUG');
?>
<?=\View::instance()->render('/header.phtml'); ?>
<link rel="stylesheet" href="/css/code.css">

<h1><?=$title ?></h1>

<p>
<em><?=$e['status']?></em><br/>
We're sorry but an error occurred.
</p>

<?php if ($f3->get('app.env') !== 'production'): ?>
    <?php if ($debug > 0): ?>

        <h2>Error Context</h2>
        <pre>
        <?=$e['text'] ?>
        </pre>

    <?php endif ?>

    <?php if ($debug > 1): ?>

        <h2>Error Trace</h2>
        <pre>
            <?=print_r($f3->trace(null, false)); ?>
        </pre>

    <?php endif ?>

<?php endif ?>

<?=\View::instance()->render('/footer.phtml'); ?>
