<?php echo \View::instance()->render('views/header.phtml'); ?>

<h1>f3-boilerplate</h1>

<h2>Documentation</h2>
<ul>
    <li><a href="/doc/README">README</a></li>
    <li><a href="/doc/CHANGES">CHANGES</a></li>
    <li><a href="/doc/TODO">TODO</a></li>
    <li><a href="/doc/ROADMAP">ROADMAP</a></li>
    <li><a href="/doc/LICENSE">LICENSE</a></li>
    <li><a href="/doc/CREDITS">CREDITS</a></li>
</ul>

<h2>PHPINFO</h2>

<?php phpinfo() ?>

<?php echo \View::instance()->render('views/footer.phtml'); ?>
