<?php echo \View::instance()->render('views/header.phtml'); ?>

<h1>f3-boilerplate</h1>

<?php printf("<p>Language: %s, Country: %s</p>", \Base::instance()->get('SESSION.language'), \Base::instance()->get('SESSION.country')) ?>

<h2>Switch Language</h2>
<ul>
    <li><a href="<?php echo \helpers\URL::i18n('', 'es', 'es') ?>">Spanish</a></li>
    <li><a href="<?php echo \helpers\URL::i18n('', 'en', 'gb') ?>">English (GB)</a></li>
    <li><a href="<?php echo \helpers\URL::i18n('', 'sv', 'se') ?>">Swedish</a></li>
</ul>

<h2>Documentation</h2>
<ul>
    <li><a href="/documentation/README">README</a></li>
    <li><a href="/documentation/CHANGES">CHANGES</a></li>
    <li><a href="/documentation/TODO">TODO</a></li>
    <li><a href="/documentation/ROADMAP">ROADMAP</a></li>
    <li><a href="/documentation/LICENSE">LICENSE</a></li>
    <li><a href="/documentation/CREDITS">CREDITS</a></li>
</ul>

<h2>PHPINFO</h2>

<?php phpinfo() ?>

<?php echo \View::instance()->render('views/footer.phtml'); ?>
